apiVersion: v1
kind: ConfigMap
metadata:
  name: svn-configmap
data:
   AuthLDAPBindDN: "uid=example,dc=example,dc=com"
   AuthLDAPBindPassword: "strong_password"
   AuthLDAPURL: "ldap://your.ldap.server:389/ou=people,dc=example,dc=com?uid?sub?(objectClass=*)"
   LdapGroup: "cn=group_of_allowed_to_modify_users,ou=groups,dc=example,dc=com"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-svn-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/svn/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-svn-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svn
  labels:
    app: svn
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: svn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svn
  labels:
    app: svn
spec:
  revisionHistoryLimit: 3  # removes old replicasets for deployment rollbacks
  strategy:
    rollingUpdate:
      maxUnavailable: 0  # Avoid Terminating and ContainerCreating at the same time
  selector:
    matchLabels:
      app: svn
  template:
    metadata:
      labels:
        app: svn
    spec:
      nodeSelector:
        svn-data: "true"
      containers:
        - name: svn
          image: mikolaw/svnldap:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
               name: svn-configmap
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 60
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /opt
              name: svn-data
      volumes:
        - name: svn-data
          persistentVolumeClaim:
            claimName: storage-svn-data
